

CREATE TABLE estado(
	id SERIAL PRIMARY KEY,
	sigla VARCHAR(2) NOT NULL UNIQUE ,
	nome VARCHAR(100) 
);

CREATE TABLE cidade(
	id SERIAL PRIMARY KEY,
	nome VARCHAR(100) NOT NULL UNIQUE,
	id_estado SERIAL REFERENCES estado(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE endereco(
	id SERIAL PRIMARY KEY,
	logradouro VARCHAR(100) NOT NULL,
	numero VARCHAR(5)NOT NULL,
	bairro VARCHAR (100) NOT NULL,
	complemento VARCHAR(100),
	cep VARCHAR(9) NOT NULL,
	id_cidade SERIAL NOT NULL REFERENCES cidade(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE usuario(
	ID SERIAL PRIMARY KEY,
	nome VARCHAR(150) NOT NULL,
	email VARCHAR(150) NOT NULL UNIQUE,
	data_nascimento  DATE NOT NULL,
	senha VARCHAR(30) NOT NULL,
	ativo BOOLEAN ,
	data_cadastro DATE NOT NULL,
	data_atualizacao DATE,
	Telefone1 VARCHAR(15)  NOT NULL UNIQUE ,
	Telefone2 VARCHAR(15) UNIQUE,
	foto VARCHAR(255),
	cpf VARCHAR(11) UNIQUE,
	termo BOOLEAN NOT NULL,
	id_endereco SERIAL NOT NULL REFERENCES endereco(id) ON UPDATE CASCADE ON DELETE NO ACTION
	);

CREATE TABLE livro(
	id SERIAL PRIMARY KEY,
	Titulo VARCHAR(100) NOT NULL,
	numero_paginas INTEGER NOT NULL,
	autor VARCHAR(100) NOT NULL,
	preco DOUBLE PRECISION NOT NULL ,
	data_Compra DATE,
	situacao_compra INTEGER CHECK(situacao_compra IN(1,2,3,4,5,6,7)) NOT NULL,
	situacao_atual INTEGER CHECK(situacao_atual IN(1,2,3,4,5,6,7)) NOT NULL,
	id_usuario SERIAL NOT NULL REFERENCES usuario(id) ON UPDATE CASCADE ON DELETE NO ACTION
);

CREATE TABLE categoria(
	id SERIAL PRIMARY KEY,
	tipo INTEGER CHECK(tipo IN(1,2,3,4,5,6,7)) NOT NULL
);
CREATE TABLE categoria_livro(
	id_categoria SERIAL NOT NULL REFERENCES categoria(id) ON UPDATE CASCADE ON DELETE NO ACTION,
	id_livro SERIAL NOT NULL REFERENCES livro(id) ON UPDATE CASCADE ON DELETE NO ACTION,
	PRIMARY KEY(id_categoria,id_livro)
);	


	